dist: xenial
language: python
cache: pip
sudo: false
env:
    - DJANGO_VERSION=1.10
    - DJANGO_VERSION=1.11
python:
    - "3.4"
    - "3.5"
    - "3.6"
services:
    - postgresql
    - docker
    - xvfb

matrix:
    include:
        - python: "3.6"
          env:
              - TEST_SUITE=elasticsearch
              - DJANGO_VERSION=1.11
        - python: "3.6"
          env:
              - TEST_SUITE=solr
              - DJANGO_VERSION=1.11
        - node_js: "lts/*"
          language: node_js
          python: ""
          addons:
              firefox: "52.0.2esr"
          env: TEST_SUITE=js_unittests
        - node_js: "lts/*"
          language: node_js
          python: ""
          addons:
              firefox: latest-esr
          env: TEST_SUITE=js_unittests
        - addons:
              firefox: "60.2.2esr"
          env:
              - TEST_SUITE=selenium
              - DJANGO_VERSION=1.11

install:
    - . src/ci_scripts/travis_install.sh

before_script:
    - . src/ci_scripts/travis_before_script.sh

script:
    - src/ci_scripts/travis.sh

after_success:
    - src/ci_scripts/travis_after_success.sh

branches:
    only:
        - develop
